### ISSUE TITLE
Utiliser YAML pour le fichier de scénario

### ISSUE THREAD

**Issue by n-peugnet** [Atlaoui/ParallelProgramingInterface#34]
Relié à #33 et #31.

YAML est un sur ensemble de json beaucoup plus agréable à lire par un être humain.
ça transforme par exemple ça :

```json
{
	"events": [
		{
			"args": [],
			"FunctionName": "doSomething",
			"Node": 1,
			"Delay": 1
		},
		{
			"args": [],
			"FunctionName": "doSomething",
			"Node": 2,
			"Delay": 1
		}
	],
	"failures": [
		{
			"Node": 1
		}
	]
}
```

En :

```yaml
events:
  - args: []
    FunctionName: doSomething
    Node: 1
    Delay: 1
  - args: []
    FunctionName: doSomething
    Node: 2
    Delay: 1
failures:
  - Node: 1
```
